# Generated by Django 4.2.4 on 2023-08-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script_data.script')),
            ],
        ),
    ]
